import ffmpeg
import os
import shutil
from tools.unitman import B_to_MB
from math import floor

def check_ffmpeg():
    """Check if ffmpeg is installed and accessible."""
    for cmd in ["ffmpeg", "ffprobe"]:
        if not shutil.which(cmd):
            print(f"Error: {cmd} is not installed or not in PATH.")
            raise Exception(f"{cmd} not found")

def get_media_info(input_file: str):
    """Gets file size, duration, video bitrate and audio bitrate using ffmpeg probe."""
    try:
        probe = ffmpeg.probe(input_file)

        duration_s = int(floor(float(probe['format']['duration'])))
        file_size_bytes = int(probe['format']['size'])
        file_size_mb = B_to_MB(file_size_bytes)

        video_stream = next(s for s in probe['streams'] if s['codec_type'] == 'video')
        audio_stream = next(s for s in probe['streams'] if s['codec_type'] == 'audio')

        video_kbps = int(video_stream['bit_rate']) // 1000
        audio_kbps = int(audio_stream['bit_rate']) // 1000

        return file_size_mb, duration_s, video_kbps, audio_kbps
    except (ffmpeg.Error, ValueError, StopIteration) as e:
        print(f"Error: {e}")
        raise

def compress_video(input_file: str, output_file: str, target_video_bitrate_kbps: int, target_audio_bitrate_kbps: int):
    """Two pass video compression to target video and audio bitrates."""
    try:
        print("PASS 1: Analyzing...")
        (
            ffmpeg
            .input(input_file)
            .output(
                os.devnull,
                vcodec='libx264',
                **{'b:v': f'{target_video_bitrate_kbps}k'},
                an=None,
                f='mp4',
                **{'pass': 1}
            )
            .overwrite_output()
            .global_args('-loglevel', 'error')
            .run()
        )

        print("PASS 2: Compressing...")
        (
            ffmpeg
            .input(input_file)
            .output(
                output_file,
                vcodec='libx264',
                **{'b:v': f'{target_video_bitrate_kbps}k'},
                acodec='aac',
                **{'b:a': f'{target_audio_bitrate_kbps}k'},
                f='mp4',
                **{'pass': 2}
            )
            .overwrite_output()
            .global_args('-loglevel', 'error')
            .run()
        )
    except ffmpeg.Error as e:
        print(f"Error: {e}")

def clear_logs():
    """Clears log files generated by ffmpeg during compression."""
    for f in ["ffmpeg2pass-0.log", "ffmpeg2pass-0.log.mbtree"]:
        if os.path.exists(f):
            os.remove(f)